### PR TITLE
Fix subtask pull-requests

### PR DESCRIPTION
**Pull request by rjbeers**
Also addresses:
* Update old dependencies except lodash
* Add browserify-shim, because of lscache
* Cleanup babel configuration

### CODE REVIEW

**Comment by dylang** [comment]
Oh wow, nice work! 

I haven't touched this project because we use a newer version of JIRA and pretty much everything this does is now built in.

That also means I don't have any way to test your changes. 

I'll try to update it tomorrow.

**Comment by rjbeers** [comment]
@nowells, want to test it?

**Comment by nowells** [comment]
:shipit: works for me!

**Comment by dylang** [comment]
@r33beers I'm having trouble building it and I don't have time to debug - any ideas?

```
~/projects/old projects/jira-improved ✗ master ❯ yarn run build
yarn run v1.2.1
$ gulp build
[08:06:17] Using gulpfile ~/projects/old projects/jira-improved/gulpfile.js
[08:06:17] Starting 'bump'...
[08:06:17] Bumped 2.0.10 to 2.0.11 with type: patch
[08:06:17] Finished 'bump' after 19 ms
[08:06:17] Starting 'manifest'...
[08:06:17] Finished 'manifest' after 16 ms
[08:06:17] Starting 'browserify-minified'...

events.js:182
      throw er; // Unhandled 'error' event
      ^
GulpUglifyError: unable to minify JavaScript
    at createError (/Users/dgreene/projects/old projects/jira-improved/node_modules/gulp-uglify/lib/create-error.js:6:14)
    at apply (/Users/dgreene/projects/old projects/jira-improved/node_modules/gulp-uglify/node_modules/lodash/_apply.js:16:25)
    at wrapper (/Users/dgreene/projects/old projects/jira-improved/node_modules/gulp-uglify/node_modules/lodash/_createCurry.js:41:12)
    at /Users/dgreene/projects/old projects/jira-improved/node_modules/gulp-uglify/lib/minify.js:54:15
    at DestroyableTransform._transform (/Users/dgreene/projects/old projects/jira-improved/node_modules/gulp-uglify/composer.js:10:23)
    at DestroyableTransform.Transform._read (/Users/dgreene/projects/old projects/jira-improved/node_modules/readable-stream/lib/_stream_transform.js:182:10)
    at DestroyableTransform.Transform._write (/Users/dgreene/projects/old projects/jira-improved/node_modules/readable-stream/lib/_stream_transform.js:170:83)
    at doWrite (/Users/dgreene/projects/old projects/jira-improved/node_modules/readable-stream/lib/_stream_writable.js:406:64)
    at writeOrBuffer (/Users/dgreene/projects/old projects/jira-improved/node_modules/readable-stream/lib/_stream_writable.js:395:5)
    at DestroyableTransform.Writable.write (/Users/dgreene/projects/old projects/jira-improved/node_modules/readable-stream/lib/_stream_writable.js:322:11)
```

**Comment by rjbeers** [comment]
@dylang I've opened https://github.com/dylang/jira-improved/pull/7 as a possible work around.

**Pull request merged**
