### PR TITLE
Add support to search by name on avatars

### PR DESCRIPTION
**Pull request by mintyPT**

### CODE REVIEW

**Comment by dylang** [comment]
Hi, thanks for doing this, I'm sure it couldn't have been easy to figure out with my crappy code and no tests. I'm not going to merge it in because support is already included. Maybe an unrelated change - adding tipsy to the avatars - fixed this.

**Comment by mintyPT** [comment]
Actually it was easy. Simply searched for what I was looking for. What do you mean by "support is already included"?

**Comment by dylang** [comment]
> Actually it was easy. Simply searched for what I was looking for.

That's good to hear.

> What do you mean by "support is already included"?

If you type a user's name it should filter on that user without requiring this PR.

**Comment by mintyPT** [comment]
If you type the username of the user in the app filter? I  must have missed something.

**Pull request closed without merging**
